// <auto-generated />
namespace Datos.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class agreguealgo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agreguealgo));
        
        string IMigrationMetadata.Id
        {
            get { return "201607082053103_agregue-algo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
